version: '3.8'
services:
  nagios:
    build: .
    environment:
      - TZ=America/New_York
      - NAGIOS_PASSWORD=P@ssw0rd!
    ports:
      - target: 80
        published: 8080
    volumes:
      - ./../nagios:/usr/local/nagios/etc
      - ./.docker/var:/usr/local/nagios/var
