version: '3.8'
services:
  nagios:
    #build: .
    image: 'dcjulian29/nagios:latest'
    environment:
      - TZ=America/New_York
      - NAGIOS_PASSWORD=P@ssw0rd!
    ports:
      - target: 80
        published: 8080
    volumes:
      - ./.docker/nagios:/usr/local/nagios/etc
      #- /c/code/nagios:/usr/local/nagios/etc
