name: Build Image

'on':
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Grab the Nagios version to use.
        id: nagios
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Grab the NRPE version to use.
        id: nrpe
        run: echo "version=$(cat VERSION_NRPE)" >> $GITHUB_OUTPUT

      - name: Grab the Plugin version to use.
        id: plugin
        run: echo "version=$(cat VERSION_PLUGIN)" >> $GITHUB_OUTPUT

      - name: Get timestamp for CI tag
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Build the Nagios image.
        uses: docker/build-push-action@v6.3.0
        with:
          build-args: |
            NAGIOS_VERSION=${{ steps.nagios.outputs.version }}
            NRPE_VERSION=${{ steps.nrpe.outputs.version }}
            PLUGIN_VERSION=${{ steps.plugin.outputs.version }}
          tags: dcjulian29/nagios:${{ steps.nagios.outputs.version }}-${{ steps.format-time.outputs.replaced }}

      - name: Build the Nagios Plugins image.
        uses: docker/build-push-action@v6.3.0
        with:
          build-args: |
            NAGIOS_VERSION=${{ steps.nagios.outputs.version }}-${{ steps.format-time.outputs.replaced }}
          context: plugins/
          tags: dcjulian29/nagios:${{ steps.nagios.outputs.version }}-${{ steps.format-time.outputs.replaced }}-plugins

  release:
    if: contains(github.ref, 'tags/')
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub.
        uses: docker/login-action@v3
        with:
          username: dcjulian29
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Grab the image version to use.
        id: vars
        run: echo "version=$(echo ${GITHUB_REF:10})" >> $GITHUB_OUTPUT

      - name: Grab the Nagios version to use.
        id: nagios
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Grab the NRPE version to use.
        id: nrpe
        run: echo "version=$(cat VERSION_NRPE)" >> $GITHUB_OUTPUT

      - name: Grab the Plugin version to use.
        id: plugin
        run: echo "version=$(cat VERSION_PLUGIN)" >> $GITHUB_OUTPUT

      - name: Build the Nagios image.
        uses: docker/build-push-action@v6.3.0
        with:
          build-args: |
            NAGIOS_VERSION=${{ steps.nagios.outputs.version }}
            NRPE_VERSION=${{ steps.nrpe.outputs.version }}
            PLUGIN_VERSION=${{ steps.plugin.outputs.version }}
          push: true
          tags: dcjulian29/nagios:${{ steps.vars.outputs.version }},dcjulian29/nagios:latest

      - name: Build the Nagios Plugin image.
        uses: docker/build-push-action@v6.3.0
        with:
          build-args: |
            NAGIOS_VERSION=${{ steps.nagios.outputs.version }}
          context: plugins/
          push: true
          tags: dcjulian29/nagios:${{ steps.vars.outputs.version }}-plugins,dcjulian29/nagios:latest-plugins
