name: Release Image

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub.
        uses: docker/login-action@v2
        with:
          username: dcjulian29
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Grab the image version to use.
        id: vars
        run: echo "version=$(echo ${GITHUB_REF:10})" >> $GITHUB_OUTPUT

      - name: Grab the Nagios version to use.
        id: nagios
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Grab the NRPE version to use.
        id: nrpe
        run: echo "version=$(cat VERSION_NRPE)" >> $GITHUB_OUTPUT

      - name: Grab the Plugin version to use.
        id: plugin
        run: echo "version=$(cat VERSION_PLUGIN)" >> $GITHUB_OUTPUT

      - name: Build the Nagios image.
        uses: docker/build-push-action@v4.1.1
        with:
          build-args: |
            NAGIOS_VERSION=${{ steps.nagios.outputs.version }}
            NRPE_VERSION=${{ steps.nrpe.outputs.version }}
            PLUGIN_VERSION=${{ steps.plugin.outputs.version }}
          push: true
          tags: dcjulian29/nagios:${{ steps.vars.outputs.version }},dcjulian29/nagios:latest

      - name: Build the Nagios Plugin image.
        uses: docker/build-push-action@v4.1.1
        with:
          build-args: |
            NAGIOS_VERSION=${{ steps.nagios.outputs.version }}
          context: plugins/
          push: true
          tags: dcjulian29/nagios:${{ steps.vars.outputs.version }}-plugins,dcjulian29/nagios:latest-plugins
